name: CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "ci" ]

jobs:
  guix-build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Install Guix
      uses: PromyLOPh/guix-install-action@v1.5
    - name: Install GNU Make
      run: guix install make
    - name: Test
      run: make test
    - name: Build
      run: make build
