name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  guix-build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Guix
      run: sudo apt-get install -y guix make
    - uses: actions/checkout@v3
    - name: Test
      run: make test
    - name: Build
      run: guix build -f guix.scm
